services:
  asr-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8020
